[tools]
clang = "latest"
clang-format = "latest"
cmake = "latest"
ninja = "latest"

[env]
# `mise` has a built-in variable called `config_root` that allows you 
# to get the absolute path to the location of this `mise.toml` file
PROJECT_ROOT = "{{config_root}}"

[shell_alias]
build = "mise build-file"
run = "mise run-file"
