[env]
PROJECT_NAME = "d05-my-prefered-method"

[tools]
clang = "latest"
clang-format = "latest"
cmake = "latest"
ninja = "latest"

[shell_alias]
build = "mise build"
clean = "mise clean"
run = "mise run-bin"
